HEIGHT = 42
WIDTH = 90
PADDLE_POS_Y = 2
PADDLE_POS_X = 40
BALL_POS_Y = 3
BALL_POS_X = 45
BRICK_LEVEL_1_NO = 4
BRICK_LEVEL_2_NO = 2
BRICK_LEVEL_3_NO = 1
BRICK_START_Y_1 = 39
BRICK_START_X_1 = [17]
BRICK_START_Y_2 = 30
BRICK_START_X_2 = [25]
BRICK_START_Y_3 = 20
BRICK_START_X_3 = [33]

for i in range(1,BRICK_LEVEL_1_NO):
    BRICK_START_X_1.append(BRICK_START_X_1[i-1] + 15)

for i in range(1,BRICK_LEVEL_2_NO):
    BRICK_START_X_2.append(BRICK_START_X_2[i-1] + 15)

for i in range(1,BRICK_LEVEL_3_NO):
    BRICK_START_X_3.append(BRICK_START_X_3[i-1] + 15)